### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by gutolimeira** [GeneralWadaling/Civ-style-set-by-Bucketeer#3]
The message appears that the download was done, however, the mod is not applied.

Tested on versions: 
4.2.5-patch1 (_itch.io_)
4.2.5-patch1 (_github version_)
4.2.4-patch1 (_itch.io_)

![bckstylbg](https://user-images.githubusercontent.com/64593191/186996710-6ce872c1-db40-411a-ac11-f18b1607672e.PNG)

**Comment by GeneralWadaling** [comment]
huh. I'll check what is happening.

**Comment by GeneralWadaling** [comment]
Fixed, I've updated the Nations.js with the spy names, seemed to be recently added.

**Comment by gutolimeira** [comment]
Thank you!
